const ADD_DB_SOURCE = 'CONNECTION@ADD_DB_SOURCE';
const GET_DB_SOURCES = 'CONNECTION@GET_DB_SOURCES';
const DELETE_DB_SOURCE = 'CONNECTION@DELETE_DB_SOURCE';
const CONNECT_TO_DB = 'CONNECTION@CONNECT_TO_DB';
const GET_CURRENT_CONNECTION = 'CONNECTION@GET_CURRENT_CONNECTION';

module.exports = {
  ADD_DB_SOURCE,
  GET_DB_SOURCES,
  DELETE_DB_SOURCE,
  CONNECT_TO_DB,
  GET_CURRENT_CONNECTION,
};
