const ADD_DB_SOURCE = 'ESTORE@ADD_DB_SOURCE';
const GET_DB_SOURCES = 'ESTORE@GET_DB_SOURCES';
const DELETE_DB_SOURCE = 'ESTORE@DELETE_DB_SOURCE';
const CONNECT_TO_DB = 'ESTORE@CONNECT_TO_DB';

module.exports = {
  ADD_DB_SOURCE,
  GET_DB_SOURCES,
  DELETE_DB_SOURCE,
  CONNECT_TO_DB,
};
